version: '3.8'

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/Fast_api_app
    ports:
      - 8001:81
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_test/postgres

    depends_on:
      postgres_test:
        condition: service_healthy

  postgres_test:
    image: postgres:15.1-alpine
    container_name: postgres_test
    volumes:
      - postgres_test:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      
volumes:
  postgres_test: