version: '3.8'

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/Fast_api_app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres

    depends_on:
      postgres_test:
        condition: service_healthy

  postgres_test:
    image: postgres:15.1-alpine
    container_name: my_custom_container_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      
volumes:
  postgres_data: